ALL: clean s21_grep

s21_grep:
	gcc -Wall -Werror -Wextra s21_grep.c -o s21_grep

clean:
	rm -rf s21_grep

test_func:ALL
	sh test_func_grep.sh

test_leak:ALL
	sh test_leak_grep.sh

style:
	clang-format -i s21_grep.c
	clang-format -i s21_grep.h
	clang-format -n s21_grep.c
	clang-format -n s21_grep.h